experiment:
  name: 'diffusion_handwriting_generation'
  work_dir: '~/runs'

  seed: 54321
  precision: 10
  deterministic: false


training_args:
  steps: 60000
  batch_size: 96
  seq_len: 480
  text_len: 50
  img_width: 1400
  warmup: 10000
  dropout: 0.0
  att_layers_num: 2
  channels: 128
  log_freq: 1000
  save_freq: 10000


optimizer:
  type: torch.optim.Adam
  params:
    lr: 0.0003
    weight_decay: 0.00001